### ISSUE TITLE
Training interrupts on Google Colab notebook

### ISSUE THREAD

**Issue by Feel2X** [taldatech/soft-intro-vae-pytorch#1]
Hey,
first of all, thanks for your great work!

I'm trying to run the code on a Google Colab Machine.
I'm having issues with the output of the make_dataloader() function of TFRecordsDataset when training style-soft-intro-vae.

Training works fine until iteration 210 of the first epoch. Then the notebook suddenly stops without throwing any error.
For debugging, I tried iterating over the batches without performing any code in the for loop. The Loop then succesfully iterates over all the batches. However, when I try to get a new batches object returned from make_dataloader(), the Notebook exits again, without throwing any error.

Does this issue occur for anyone else?

Edit: 
Running on an Azure VM with the same setup, but without notebook, the training works. However, it would be interesting what exactly is causing the issue with Google Colab.

Best regards

**Comment by taldatech** [comment]
Hi,
Thank you for your interest in our work. I haven't tried running the style architecture on Colab, as the code (based on ALAE) was written for multi-GPU machines, and I think this is the root of the problem when running on Colab. 
Let me know if you were able to locate the issue with Colab.
Best,
Tal
