### ISSUE TITLE
Recommended Hyper-Params for The Enc-Dec Arch on MNIST

### ISSUE THREAD

**Issue by GloryyrolG** [taldatech/soft-intro-vae-pytorch#11]
Hi Daniel,

May you check the recommendation of hyper-params for MNIST here in
https://github.com/taldatech/soft-intro-vae-pytorch/tree/main/soft_intro_vae#recommended-hyperparameters?

I just found some spurious things, like
- The training process. `kl_real > kl_fake`.
![image](https://user-images.githubusercontent.com/33202229/127247074-30e60300-58a8-4a8f-8b57-63ae2d8af9c9.png)

- Random sampling in the latent space (not perfect)
![image](https://user-images.githubusercontent.com/33202229/127247216-38a6f71c-9f37-487e-af15-4361fc254398.png)

Thanks.

**Comment by taldatech** [comment]
Thank you for noticing. I just ran it with `beta_neg=128` and it seems good. You can also try lower values for `beta_neg`.
![soft_intro_train_graphs](https://user-images.githubusercontent.com/30633883/127278009-a50858a7-098a-4385-9695-b001ceb37e61.jpg)

![image_91000](https://user-images.githubusercontent.com/30633883/127278100-dffb4e17-c84d-4e08-a26d-f1c0644593ad.jpg)

**Comment by GloryyrolG** [comment]
But actually we can see random samples may not be like MNIST training data (the last two rows), or not converge to the true data distribution, though the reconstruction seems good still. I mean, at least under this circumstance (relatively easy MNIST), vanilla VAE may do better in terms of approximating true $p(x)$. Right?

**Comment by taldatech** [comment]
Unless you measure this quantitatively (e.g., FID or something like that), this stays in the eye of the observer. I think the samples are good, you can train a vanilla VAE and compare. Moreover, if you take a look at the paper, you will find out the our model does not converge to the data distribution, but to an entropy-regularized version of it.

**Comment by GloryyrolG** [comment]
True, I read the paper before. Below is a snapshot of sampled images by vanilla VAE. Actually, I think some rotation angles and strikes in S-IntroVAE generated images are kinda not likely to be seen in real handwriting. However, those generated by vanilla VAE also a bit suffer the blur problem. Btw, I think human judgement is still an important and faithful measurement.

Thanks, Daniel.

![image](https://user-images.githubusercontent.com/33202229/127283932-6201f19d-a20f-431e-ae58-d2dc5cc4d7c5.png)
