### ISSUE TITLE
generate function parameters

### ISSUE THREAD

**Issue by mparmis** [taldatech/soft-intro-vae-pytorch#12]
Hi,

Can you please tell me what the parameters "lod" and "blend_factor" are in /style_soft_intro_vae/model.py line 159 (generate function). 

Thank you

**Comment by taldatech** [comment]
Hi,
These are taken straight away from the ALAE paper, and are explained there.
Basically:
* LOD (Level of Depth, I think the "D" is for depth) - the current resolution we are training. e.g., lood is 4x4 resolution, lod 1 is 8x8 and so on...
* blend - this is the parmeter we use to bkend between resolutions as this is a progressive growing architecture. So when you see blend=0.1 it means we are taking 0.9 * (lod-1) + 0.1 *(lod), blending the pixels from sequential lod. For example, when transioning between lod 0 and lod 1, we upscale the 4x4 to 8x8 and take 0.9 * (upscaled 4x4) + 0.1 * (8x8).

**Comment by mparmis** [comment]
Thank you.
