### ISSUE TITLE
Some Question about smooth interpolation Fig.17

### ISSUE THREAD

**Issue by chokyungjin** [taldatech/soft-intro-vae-pytorch#2]
Thank you so much for open source code!
But I have a question. In your paper, you said that you created the following images with smooth interference,
how did you do it? Can you give me the code? 
![image](https://user-images.githubusercontent.com/46750574/104802252-0320bf00-5814-11eb-97cf-9af63ef6c4d9.png)

Thanks Again.

**Comment by taldatech** [comment]
Hi,
You can find the code in `style_soft_intro_vae/make_figures/make_recon_figure_interpolation.py`.
Best,
Tal

**Comment by chokyungjin** [comment]
Thanks, I'll try.
