### ISSUE TITLE
Aborted core dumped error 

### ISSUE THREAD

**Issue by chokyungjin** [taldatech/soft-intro-vae-pytorch#3]
Hi, I tried to start learning, but the following error occurred. I set requirements and my parameters are as follows. How can I solve this error?

NAME: ffhq
DATASET:
  PART_COUNT: 1
  SIZE: 85965
  FFHQ_SOURCE: 
/workspace/data/train_tf/
  PATH: /workspace/data/train_tf/

  PART_COUNT_TEST: 1
  PATH_TEST: /workspace/data/test_tf/

  SAMPLES_PATH: /workspace/data/test/
  STYLE_MIX_PATH: ./style_mixing

  MAX_RESOLUTION_LEVEL: 8
MODEL:
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 7
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 64
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
  BETA_KL: 0.2
  BETA_REC: 0.1
  BETA_NEG: [2048,  2048,   2048,   1024,  512,   512,     512,    512,    512]
  SCALE: 0.000005
OUTPUT_DIR: ./output
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 2
  NUM_VAE: 1
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 300
  #                    4    8   16    32    64    128    256
  LOD_2_BATCH_8GPU: [512, 256, 128,   64,   32,    32,    32,       32,        32] # If GPU memory ~16GB reduce last number from 32 to 24
  LOD_2_BATCH_4GPU: [ 512,    256,     128,      64,      32,       32,        16,       8,        4 ]
  LOD_2_BATCH_2GPU: [ 128,    128,     128,      64,      32,       16,        8 ]
  LOD_2_BATCH_1GPU: [ 32,    32,     32,      32,      16,       8,         4 ]

  LEARNING_RATES: [0.0015,  0.0015,   0.0015,   0.0015,  0.0015,   0.0015,     0.002,     0.003,    0.003]

2021-01-16 14:11:11,875 logger INFO: Running with config:
DATASET:
  FFHQ_SOURCE: /workspace/data/train_tf/
  FLIP_IMAGES: False
  MAX_RESOLUTION_LEVEL: 8
  PART_COUNT: 1
  PART_COUNT_TEST: 1
  PATH: /workspace/data/train_tf/
  PATH_TEST: /workspace/data/test_tf/
  SAMPLES_PATH: /workspace/data/test/
  SIZE: 85965
  SIZE_TEST: 25000
  STYLE_MIX_PATH: ./style_mixing
MODEL:
  BETA_KL: 0.2
  BETA_NEG: [2048, 2048, 2048, 1024, 512, 512, 512, 512, 512]
  BETA_REC: 0.1
  CHANNELS: 3
  DLATENT_AVG_BETA: 0.995
  ENCODER: EncoderDefault
  GENERATOR: GeneratorDefault
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 7
  MAPPING_FROM_LATENT: MappingFromLatent
  MAPPING_LAYERS: 8
  MAPPING_TO_LATENT: MappingToLatent
  MAX_CHANNEL_COUNT: 512
  SCALE: 5e-06
  START_CHANNEL_COUNT: 64
  STYLE_MIXING_PROB: 0.9
  TRUNCATIOM_CUTOFF: 8
  TRUNCATIOM_PSI: 0.7
  Z_REGRESSION: False
NAME: ffhq
OUTPUT_DIR: ./output
PPL_CELEBA_ADJUSTMENT: False
TRAIN:
  ADAM_BETA_0: 0.0
  ADAM_BETA_1: 0.99
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 2
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  LEARNING_RATES: [0.0015, 0.0015, 0.0015, 0.0015, 0.0015, 0.0015, 0.002, 0.003, 0.003]
  LOD_2_BATCH_1GPU: [32, 32, 32, 32, 16, 8, 4]
  LOD_2_BATCH_2GPU: [128, 128, 128, 64, 32, 16, 8]
  LOD_2_BATCH_4GPU: [512, 256, 128, 64, 32, 32, 16, 8, 4]
  LOD_2_BATCH_8GPU: [512, 256, 128, 64, 32, 32, 32, 32, 32]
  NUM_VAE: 1
  REPORT_FREQ: [100, 80, 60, 30, 20, 10, 10, 5, 5]
  SNAPSHOT_FREQ: [300, 300, 300, 100, 50, 30, 20, 20, 10]
  TRAIN_EPOCHS: 300
Running on  Quadro RTX 8000
2021-01-16 14:11:17,697 logger INFO: Trainable parameters decoder:
23984981
2021-01-16 14:11:17,698 logger INFO: Trainable parameters encoder:
26789952
2021-01-16 14:11:17,700 logger INFO: No checkpoint found. Initializing model from scratch
2021-01-16 14:11:17,700 logger INFO: Starting from epoch: 0
2021-01-16 14:11:18,534 logger INFO: ################################################################################
2021-01-16 14:11:18,534 logger INFO: # Switching LOD to 0
2021-01-16 14:11:18,534 logger INFO: # Starting transition
2021-01-16 14:11:18,534 logger INFO: ################################################################################
2021-01-16 14:11:18,534 logger INFO: ################################################################################
2021-01-16 14:11:18,534 logger INFO: # Transition ended
2021-01-16 14:11:18,535 logger INFO: ################################################################################
beta negative changed to: 2048
2021-01-16 14:11:18,535 logger INFO: Batch size: 32, Batch size per GPU: 32, LOD: 0 - 4x4, blend: 1.000, dataset size: 85965
Aborted (core dumped)

**Comment by taldatech** [comment]
Can you please try the config file we provide? It seems something wrong with the data loading. We use ALAE's (https://github.com/podgorskiy/ALAE) data splitting of the TFRecords files (16 part count).

**Comment by chokyungjin** [comment]
When I used Single GPU, an Aborted (core dumped) error occurred, and when I used two GPUs, an Exception: process 0 terminated with signal SIGABRT error occurred. 
I only modified the part count. Is this the cause of data loading?

**Comment by taldatech** [comment]
I think so. Notice the differences between our config to yours (not only the part count, but also the path). You should start by using our config and then modify to accommodate to your needs. ALAE provide a code for splitting the TFRecords files. As you may have noticed, the dataloader is written to support TFRecords files, which is different than the way we usually load data in PyTorch, so I think you should look there if you want to change it.

**Comment by chokyungjin** [comment]
Ok, I modified my config and tfrecords, But I stiil not running code. If you don't mind, can I ask if there is a dockerfile? I'm not conda user, So I set the requirements.text.
Thanks.

**Comment by taldatech** [comment]
I'm sorry you are unable to run the code. Did you follow the environment installation instructions of ALAE (https://github.com/podgorskiy/ALAE)?

Another thing I suggest, is downloading the pre-trained checkpoints, and try to generate data with them. This will tell you if the problem you are facing is with the dataloader or something else.
I ran to code again to make sure it works, and it works (though I'm using Anaconda).

Unfortunately, I don't have a Docker file to provide you with, but if you are able to train ALAE, there should be no problem with training our model (just follow the installation instructions).

**Comment by chokyungjin** [comment]
Well, I set it to conda and tried to start learning again, but the same error occurred. 
So I'll try to generate using pre-trained model. How Can I test(generate) in your open pre-trained model? 
I'm downloading your pre-trained model.
Thanks.

**Comment by taldatech** [comment]
Follow the instructions in the README file, and use `style_soft_intro_vae/make_figures/make_generation_figure.py` to generate images using the checkpoint. Make sure to set the correct paths.

Also, are you able to train ALAE or generate from a pre-trained ALAE model?

**Comment by chokyungjin** [comment]
No, I did not train ALAE.
I generated the image using the pre-trained model. The result was little strange, but there was no error.
Is there still a problem with me? What else can I do?

**Comment by taldatech** [comment]
Then I assume the problem is with the data loading. Did you try to train both on FFHQ and CelebHQ? did you install `DareBlopy` (`pip install dareblopy`)?

**Comment by chokyungjin** [comment]
Yes, I installed DareBlopy (pip install dareblopy). But I didn't try to train FFHQ or Celeba. I'll try.

**Comment by chokyungjin** [comment]
Hi, @taldatech. I downloaded celeba_hq and generated image successfully. 
But after converting to tfrecords, I still couldn't train.
If you don't mind, can you show me pip list? 
I think my problem are data loading and environments.

One more thing, My cuda version is 11.1, Can this be a problem?

**Comment by taldatech** [comment]
CUDA version: 10.0
pip list:

Package              Version
-------------------- -------------------
absl-py              0.9.0
astor                0.8.1
atari-py             0.2.6
box2d-py             2.3.8
certifi              2020.6.20
cffi                 1.14.0
chardet              3.0.4
cloudpickle          1.3.0
cma                  3.0.3
cycler               0.10.0
Cython               0.29.19
dareblopy            0.0.3
dnnlib               0.0.1
future               0.18.2
gast                 0.3.3
glfw                 1.11.2
grpcio               1.30.0
h5py                 2.10.0
idna                 2.10
imageio              2.8.0
importlib-metadata   1.7.0
joblib               0.16.0
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
kiwisolver           1.2.0
lmdb                 1.0.0
lockfile             0.12.2
Markdown             3.2.2
matplotlib           3.2.2
mkl-fft              1.1.0
mkl-random           1.1.1
mkl-service          2.3.0
mock                 4.0.2
numpy                1.18.5
olefile              0.46
packaging            20.4
Pillow               7.1.2
pip                  20.1.1
protobuf             3.12.2
pycparser            2.20
pyglet               1.5.0
pyparsing            2.4.7
python-dateutil      2.8.1
PyYAML               5.3.1
requests             2.24.0
scikit-learn         0.23.1
scipy                1.4.1
setuptools           47.3.1.post20200622
six                  1.15.0
tensorboard          1.13.1
tensorflow-estimator 1.13.0
tensorflow-gpu       1.13.1
termcolor            1.1.0
threadpoolctl        2.1.0
torch                1.5.1
torchvision          0.6.0a0+35d732a
tornado              6.0.4
tqdm                 4.47.0
urllib3              1.25.10
Werkzeug             1.0.1
wheel                0.34.2
yacs                 0.1.6
zipp                 3.1.0

Let me know if you were able to solve this.

**Comment by chokyungjin** [comment]
In my guess, I think there is a problem with distribution training. What should I do not use this? 
But I had a problem when I try to train on a single GPU.

**Comment by taldatech** [comment]
All the packages and CUDA version match yours? If they do, then maybe try another machine, if you have access to one.

**Comment by chokyungjin** [comment]
Hi @taldatech , I solved my problem! My problem was TFrecords loader and Second is torch distribution 'MASTER_ADDR' , 'MASTER_PORT' miss! 
Thank you.

**Comment by taldatech** [comment]
I'm very happy to hear that! Thanks for sharing the solution.
