### ISSUE TITLE
Sample image question

### ISSUE THREAD

**Issue by chokyungjin** [taldatech/soft-intro-vae-pytorch#4]
Hi, 
How should I interpret the sample image? I'm training model batch size 4, but I can't interpret each column or row. 
Thanks.

**Comment by taldatech** [comment]
row-wise:
top - real
middle - reconstruction
bottom - random sample

**Comment by chokyungjin** [comment]
Thanks, So now my model is good at reconstruction, but not random sampling.
One more question, I'm currently learning with 100,000 datasets 512 x 512 image size, how much should I train?
I read your paper and it didn't seem to say that you trained for a few days.

**Comment by taldatech** [comment]
We actually didn't have the resources to run 512x512. FFHQ/Celeb-HQ at 256x256, 4 GPUs, took about 4-5 days. The balance between reconstructions and sampling is controlled by the hyperparameters.

**Comment by chokyungjin** [comment]
Could you recommend a hyperparameter for better sampling than current?

**Comment by taldatech** [comment]
We have the default hyper-parameters for the datasets we used in the config files and in the README files, so try to start from there or just by setting `beta_kl=beta_rec=1.0` and playing with the `beta_neg` hyper-paramater (try to set it to the size of `z_dim` and see what happens).

**Comment by chokyungjin** [comment]
Ok, Thanks a Million!
