### ISSUE TITLE
Can't Not find weighted sum of the extracted styles

### ISSUE THREAD

**Issue by chokyungjin** [taldatech/soft-intro-vae-pytorch#6]
Hi, I want to interpolate in latent vector w space, not latent vector in z space. 
I think your encoding code returns z space latent vector, but I want more complicated manipulation in w space.
How can I solve it?
https://github.com/taldatech/soft-intro-vae-pytorch/blob/6942a491155575e2ba4a78d550c4a85fa4a84b91/style_soft_intro_vae/make_figures/make_recon_figure_interpolation_2_images.py#L126

One more question, what is Ci learnable parameter in your code? I want to check Ci you mentioned in your paper.
Thanks.
![image](https://user-images.githubusercontent.com/46750574/108646672-033e6980-74fa-11eb-923a-882409ec59d6.png)

**Comment by taldatech** [comment]
After you encode to the latent variable `z`, you map to styles via `styles = model.mapping_fl(z)` (you can also use `mu` for a deterministic mapping). For more control over the styles, you will have to get into how the styles are collected (which is similar to ALAE's method). This process is explained in more detail in the ALAE paper. Look at the `nets` file, to get a better understanding how to the information you need. `C_i` are learned weights (part of the Adaptive Instance Normalization).

**Comment by chokyungjin** [comment]
Thanks, but I still can not solve to find AdaIN layer. I only found pixel norm and instance norm.

**Comment by taldatech** [comment]
Take a look at the `encode()` and `encode2()` methods, and note the the `EncoderBlock` implementation (https://github.com/taldatech/soft-intro-vae-pytorch/blob/main/style_soft_intro_vae/net.py#L63)

**Comment by chokyungjin** [comment]
When I read your paper, AdaIN layer was in Decoder, Not Encoder.

**Comment by taldatech** [comment]
You have the SAME in the Decoder (https://github.com/taldatech/soft-intro-vae-pytorch/blob/main/style_soft_intro_vae/net.py#L129), the whole idea is that it is somewhat symmetric.

**Comment by chokyungjin** [comment]
Oh, I understood. Thanks!

**Comment by chokyungjin** [comment]
Last question, 
Do the sample images set as "SAMPLES_PATH" in .yaml affect model training? 
I thought it was just for visualization.

**Comment by taldatech** [comment]
No, just for visualization.
